include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"

custom_lint:
  rules:
    # I will turn it on when @Dependencies won't be experimental
    - scoped_providers_should_specify_dependencies: false
    - provider_dependencies: false
