name: aac
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.7.0
  image_picker: ^1.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  flutter_riverpod: ^2.3.6
  kiosk_mode: ^0.5.0
  image_cropper: ^5.0.0
  permission_handler: ^10.4.3
  path: ^1.8.3
  device_info_plus: ^9.0.3
  wakelock_plus: ^1.1.1
  word_generator: ^0.4.3
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/default_image_file.png
    - assets/oops-steve-carell.gif
