name: aac
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2
  image_picker: ^1.0.1
  path_provider: ^2.0.15
  flutter_riverpod: ^2.5.1
  kiosk_mode: ^0.6.0
  image_cropper: ^9.0.0
  permission_handler: ^11.3.1
  path: ^1.8.3
  device_info_plus: ^11.3.0
  # wakelock_plus: ^1.2.10
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^3.11.0
  firebase_crashlytics: ^4.3.2
  http: ^1.3.0
  riverpod_annotation: ^2.6.1
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  word_generator:
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  # custom_lint: ^0.5.11
  riverpod_lint: ^2.6.4
  riverpod_generator: ^2.6.4
  flutter_launcher_icons: ^0.14.3
  drift_dev: ^2.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/default_image_file.png
    - assets/oops-steve-carell.gif
    - assets/could-not-find-anything-symbol-arrasac.png
