name: aac
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  image_picker: ^1.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  flutter_riverpod: ^2.5.1
  kiosk_mode: ^0.5.0
  image_cropper: ^5.0.0
  permission_handler: ^11.3.1
  path: ^1.8.3
  device_info_plus: ^10.1.0
  wakelock_plus: ^1.1.1
  word_generator: ^0.4.3
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  http: ^1.1.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
  custom_lint: ^0.5.11
  riverpod_lint: ^2.1.1
  riverpod_generator: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/default_image_file.png
    - assets/oops-steve-carell.gif
    - assets/could-not-find-anything-symbol-arrasac.png
