// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzMfZpJjPM0NRkddoK0mvSVQAnDqnkRPk',
    appId: '1:826800469394:web:85f83e336ebe2cfd4e7d4b',
    messagingSenderId: '826800469394',
    projectId: 'gadacz-2a486',
    authDomain: 'gadacz-2a486.firebaseapp.com',
    storageBucket: 'gadacz-2a486.appspot.com',
    measurementId: 'G-71W6HQEM3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLL74vu61uyw4S7HsHk_2t_sRyQsazlb8',
    appId: '1:826800469394:android:bad39aa8e14c6f874e7d4b',
    messagingSenderId: '826800469394',
    projectId: 'gadacz-2a486',
    storageBucket: 'gadacz-2a486.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0EtFU81EibH30lV0zQBnZUTfkI6EjwUg',
    appId: '1:826800469394:ios:27896feb45c59ee84e7d4b',
    messagingSenderId: '826800469394',
    projectId: 'gadacz-2a486',
    storageBucket: 'gadacz-2a486.appspot.com',
    iosBundleId: 'com.example.aac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0EtFU81EibH30lV0zQBnZUTfkI6EjwUg',
    appId: '1:826800469394:ios:d8aabf0a787de2ad4e7d4b',
    messagingSenderId: '826800469394',
    projectId: 'gadacz-2a486',
    storageBucket: 'gadacz-2a486.appspot.com',
    iosBundleId: 'com.example.aac.RunnerTests',
  );
}
